# Generated by Django 4.2.5 on 2023-09-15 17:18

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos', validators=[video.models.validate_mp4_extension]),
        ),
    ]
