# Generated by Django 4.2.5 on 2023-09-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
