# Generated by Django 4.2.5 on 2023-09-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_hls_video_is_processed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='is_processed',
            new_name='is_running',
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
